WCCILdata    (0), 2022.04.05 16:34:25.355, SYS,  INFO,        1, Manager Start, PROJ, Test, V 3.18 - 3.18   platform Windows AMD64 linked at Dec 14 2021 20:28:12 (f190776a789)
WCCILdata    (0), 2022.04.05 16:34:25.362, SYS,  INFO,        0, , (Re)Opening databases in single user mode without transaction logging.
WCCILdata    (0), 2022.04.05 16:34:26.604, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2022.04.05 16:34:26.605, SYS,  INFO,        0, , Initialize archive smoothing
WCCILdata    (0), 2022.04.05 16:34:26.605, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2022.04.05 16:34:26.606, SYS,  INFO,        0, , Initializing last value cache
WCCILdata    (0), 2022.04.05 16:34:26.607, SYS,  INFO,        0, , Loading internal datapoints
WCCILdata    (0), 2022.04.05 16:34:26.607, SYS,  WARNING,    33, General error in Data Manager, DataManDpIntern, loadInternalDp, Internal DPE not found: _DataManager.DataBase.Check:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.608, SYS,  INFO,        0, , Initializing ID history
WCCILdata    (0), 2022.04.05 16:34:26.608, SYS,  INFO,        0, , Initializing Alert history
WCCILdata    (0), 2022.04.05 16:34:26.609, SYS,  INFO,        0, , Initializing Alert Class cache
WCCILdata    (0), 2022.04.05 16:34:26.610, SYS,  INFO,        6, Initialization by Data Manager finished
WCCILdata    (0), 2022.04.05 16:34:26.610, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.arNr:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.610, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.state:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arType:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.arName:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.hostNameSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.filePathSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.fileNameSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.createArchive:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.general.forwardToRDB:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errNum:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errDp:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errBit:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.error.errRead:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxDpElSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxValuesSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxFillPctSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.611, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxHeapSizeSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCacheSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheGet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.size.maxCorrCacheSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.aliveInterval:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.intervals.saveCycle:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validFrom:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.validUntil:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.time:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.weekDay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.monthDay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.month:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncTime:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncWeekDay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncDay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.syncMonth:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.interval:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeGet.delay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validFrom:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.validUntil:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.time:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.612, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.weekDay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.613, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.monthDay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.613, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.month:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.613, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncTime:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.613, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileSwitch.switchTimeSet.syncWeekDay:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.613, SYS,  SEVERE,    118, Last error already repeated 50 times. Until another output occurs, this one will be blocked.
WCCILdata    (0), 2022.04.05 16:34:26.615, PARAM,SEVERE,      8, Element does not exist, problem during archive initialization, datapoint does not exist:, _ValueArchive_0.setMgmt.fileCompression.autoStartAfterSwitchSet:_original.._value
WCCILdata    (0), 2022.04.05 16:34:26.615, SYS,  INFO,      119, Last error repeated 213 times.
WCCILdata    (0), 2022.04.05 16:34:26.615, SYS,  INFO,        0, , Initializing Value Archives
WCCILdata    (0), 2022.04.05 16:34:26.615, SYS,  INFO,        0, , ValueArchive will be used...
WCCILdata    (0), 2022.04.05 16:34:28.014, SYS,  INFO,        4, Connected to (SYS: 1 Event -num 0 CONN: 1) @ DESKTOP-9P3H9IG (::1)
WCCILdata    (0), 2022.04.05 16:34:28.027, SYS,  INFO,        0, , Manager (SYS: 1 Event -num 0 CONN: 1) initialised
WCCILdata    (0), 2022.04.05 16:34:28.069, PARAM,WARNING,     7, Datapoint does not exist, UserTable, UserTable, _Users.UserId
WCCILdata    (0), 2022.04.05 16:34:28.070, PARAM,WARNING,     7, Datapoint does not exist, ManagerTable, ManagerTable, _Managers.Auth.ManType
WCCILdata    (0), 2022.04.05 16:34:28.270, SYS,  INFO,        4, Connected to (SYS: 1 Driver -num 1 CONN: 1) @ DESKTOP-9P3H9IG (::1)
WCCILdata    (0), 2022.04.05 16:34:28.278, SYS,  INFO,        0, , Manager (SYS: 1 Driver -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.05 16:34:28.527, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-9P3H9IG (::1)
WCCILdata    (0), 2022.04.05 16:34:28.528, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.05 16:34:29.073, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.05 16:34:29.215, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-9P3H9IG (::1)
WCCILdata    (0), 2022.04.05 16:34:29.219, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.05 16:34:29.819, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.05 16:34:29.958, SYS,  INFO,        4, Connected to (SYS: 1 Ascii -num 1 CONN: 1) @ DESKTOP-9P3H9IG (::1)
WCCILdata    (0), 2022.04.05 16:34:29.971, SYS,  INFO,        0, , Manager (SYS: 1 Ascii -num 1 CONN: 1) initialised
WCCILdata    (0), 2022.04.05 16:34:58.101, SYS,  WARNING,    39, Connection lost, MAN: (SYS: 1 Ascii -num 1 CONN: 1), Connection reset by peer (10054)
WCCILdata    (0), 2022.04.05 16:34:58.145, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Driver -num 1 CONN: 1), Connection closed
WCCILdata    (0), 2022.04.05 16:34:58.254, SYS,  INFO,       39, Connection lost, MAN: (SYS: 1 Event -num 0 CONN: 1), Connection closed
WCCILdata    (0), 2022.04.05 16:34:58.257, SYS,  INFO,        0, , Loading DpIdentification
WCCILdata    (0), 2022.04.05 16:34:58.270, SYS,  INFO,        2, Manager Stop
